// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreApi.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("GameStore.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fb7c267-3369-4f48-84f6-b04464f6c728"),
                            GenreId = new Guid("04075994-f276-4f05-b979-be9e1d79f979"),
                            Name = "Game Action",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("d25f5b7f-6a30-448e-b477-7dcba2a6aee8"),
                            GenreId = new Guid("7fcb0a7d-eb7a-4454-a493-eaab14106cc8"),
                            Name = "Game Adventure",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("188e5a5b-1265-4da6-af67-3360f053fd32"),
                            GenreId = new Guid("d9cca864-5103-4142-8041-08c1fca7b822"),
                            Name = "Game RPG",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("4fa4c6b0-f896-4636-b68a-d37775546476"),
                            GenreId = new Guid("a7a751d1-2e58-46cf-9504-020dac13f40a"),
                            Name = "Game Strategy",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("e31d8c36-8efb-468d-bd4a-5ff74f7ba7e5"),
                            GenreId = new Guid("38fc59a2-7530-4f18-8ae6-034016fc9c4f"),
                            Name = "Game Sports",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("300bd70a-5483-438d-ba79-0f23241df42c"),
                            GenreId = new Guid("42536eca-eb40-485d-b46b-06d37b317efa"),
                            Name = "Game Racing",
                            Price = 600m
                        });
                });

            modelBuilder.Entity("GameStore.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04075994-f276-4f05-b979-be9e1d79f979"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("7fcb0a7d-eb7a-4454-a493-eaab14106cc8"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("d9cca864-5103-4142-8041-08c1fca7b822"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("a7a751d1-2e58-46cf-9504-020dac13f40a"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("38fc59a2-7530-4f18-8ae6-034016fc9c4f"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("42536eca-eb40-485d-b46b-06d37b317efa"),
                            Name = "Racing"
                        });
                });

            modelBuilder.Entity("GameStore.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
